### PR TITLE
Fix detection of unaliased identifiers

### LINKED ISSUE #73: Automatic skipping of trash condition does not work for unaliased identifiers.

### PR DESCRIPTION
**Pull request by nicosp**
Found while trying to improve code coverage.

Fixes #73

### CODE REVIEW

File: src/Model/Behavior/TrashBehavior.php [hunk 1]
```diff
@@ -184,41 +183,40 @@ public function beforeFind(EventInterface $event, SelectQuery $query, ArrayObjec
...
      *
      * @param \Cake\ORM\Query\SelectQuery $query Query.
-     * @param string $field Trash field
      * @return bool
      */
-    protected function shouldAddTrashCondition(SelectQuery $query, string $field): bool
+    protected function shouldAddTrashCondition(SelectQuery $query): bool
     {
+        $field = $this->getTrashField(false);
+        $fieldIdentifiers = [ $field, $this->table()->aliasField($field)];
```
Comment (ADmad) [inline src/Model/Behavior/TrashBehavior.php:200]:
```suggestion
        $fieldIdentifiers = [$this->getTrashField(false), $this->getTrashField()];
```

File: src/Model/Behavior/TrashBehavior.php [hunk 2]
```diff
@@ -184,41 +183,40 @@ public function beforeFind(EventInterface $event, SelectQuery $query, ArrayObjec
...
         $addCondition = true;
 
-        $query->traverseExpressions(function ($expression) use (&$addCondition, $field): void {
-            if (!$addCondition) {
+        $query->traverseExpressions(function ($expression) use (&$addCondition, $fieldIdentifiers): void {
+            if ($addCondition === false) {
```
Comment (ADmad) [inline src/Model/Behavior/TrashBehavior.php:204]:
```suggestion
            if (!$addCondition) {
```

**Review by ADmad — COMMENTED** [review]
Please rebase your branch onto upstream master. I have updated the CI to use newer version of static analyzers

**Comment by ADmad** [comment]
@nicosp Do you have any other fixes/changes in mind? If not I can do a new release :slightly_smiling_face:

**Comment by nicosp** [comment]
@ADmad Nope :)
